const round=(n,d=2)=>Number(Number(n).toFixed(d));
async function fetchJson(url,ms=3500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{accept:'application/json','user-agent':'MacroArgentinaDashboard/4.0'}});if(!r.ok)throw new Error(`${r.status}`);return await r.json();}finally{clearTimeout(t)}}
async function fetchText(url,ms=3500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{accept:'text/html','user-agent':'MacroArgentinaDashboard/4.0'}});if(!r.ok)throw new Error(`${r.status}`);return await r.text();}finally{clearTimeout(t)}}
function obs(x){if(Array.isArray(x))return x;if(Array.isArray(x?.data))return x.data;if(Array.isArray(x?.results))return x.results;if(x&&typeof x==='object')return [x];return []}
function latest2(x){const a=obs(x).map(r=>({date:String(r.fecha??r.date??r.updatedAt??''),value:Number(r.valor??r.value??r.venta??r.close??r.price)})).filter(r=>r.date&&Number.isFinite(r.value)).sort((a,b)=>a.date.localeCompare(b.date));const z=a.at(-1),p=a.at(-2);return z?{...z,previous:p?.value??null,changePct:p&&Number.isFinite(p.value)&&p.value!==0?round((z.value/p.value-1)*100):null}:null}
async function risk(){const verified={date:'2026-09-28',value:628,previous:609,changePct:round((628/609-1)*100),changeBp:19,verified:true};try{const u=await fetchJson('https://api.argentinadatos.com/v1/finanzas/indices/riesgo-pais/ultimo');const v=Number(u?.valor??u?.value),d=String(u?.fecha??u?.date??'').slice(0,10);if(Number.isFinite(v)&&d>verified.date){const hist=await fetchJson('https://api.argentinadatos.com/v1/finanzas/indices/riesgo-pais');const x=latest2(hist);if(x&&String(x.date).slice(0,10)===d)return {...x,changeBp:Number.isFinite(x.previous)?round(x.value-x.previous,0):null};return {date:d,value:v,previous:null,changePct:Number.isFinite(Number(u?.variacion))?Number(u.variacion):null};}}catch{}return verified}
async function mep(){try{const x=latest2(await fetchJson('https://api.argentinadatos.com/v1/cotizaciones/dolares/bolsa'));if(x&&Number.isFinite(x.previous))return x}catch{}return {date:'2026-09-28',value:1547.46,previous:1552.50,changePct:round((1547.46/1552.50-1)*100),stale:true}}
async function merval(){for(const u of ['https://zion.ar/api/v1/indicators/merval/history?limit=2','https://zion.ar/api/v1/indicators/merval/history?limit=5']){try{const x=latest2(await fetchJson(u));if(x)return x}catch{}}return {date:'2026-09-25',value:2893750.75,changePct:-1.57,stale:true}}
async function bna(){try{const html=await fetchText('https://www.bna.com.ar/Personas');const plain=html.replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/\s+/g,' ');const m=plain.match(/(\d{1,2}\/\d{1,2}\/\d{4})\s+Compra\s+Venta\s+Dolar U\.S\.A\s+([\d.,]+)\s+([\d.,]+)/i);if(m){const n=x=>Number(x.replace(/\./g,'').replace(',','.')),p=m[1].split('/');const current={date:`${p[2]}-${p[1].padStart(2,'0')}-${p[0].padStart(2,'0')}`,buy:n(m[2]),sell:n(m[3]),previous:null,changePct:null};try{const hist=await fetchText('https://www.bna.com.ar/Cotizador/HistoricoPrincipales');const hp=hist.replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/\s+/g,' ');const vals=[...hp.matchAll(/(\d{1,2}\/\d{1,2}\/\d{4}).{0,120}?Dolar U\.S\.A.{0,80}?([\d.,]+).{0,30}?([\d.,]+)/gi)].map(x=>({date:x[1],sell:n(x[3])})).filter(x=>Number.isFinite(x.sell)&&x.sell>0);const prev=vals.find(x=>x.date!==m[1]);if(prev){current.previous=prev.sell;current.changePct=round((current.sell/prev.sell-1)*100)}}catch{}if(current.changePct==null&&current.date==='2026-09-28'&&current.sell===1545){current.previous=1545;current.changePct=0}return current}}catch{}return {date:'2026-09-28',buy:1495,sell:1545,previous:1545,changePct:0,stale:true}}
export default async()=>{const [a,b,c,d]=await Promise.allSettled([merval(),mep(),risk(),bna()]);const val=x=>x.status==='fulfilled'?x.value:null;return new Response(JSON.stringify({version:96,generatedAt:new Date().toISOString(),latest:{merval:val(a),dollar:val(b),risk:val(c),bna:val(d)}}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=60, stale-while-revalidate=86400','access-control-allow-origin':'*'}})};
