const round=(n,d=2)=>Number(Number(n).toFixed(d));
async function fetchJson(url,ms=3500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{accept:'application/json','user-agent':'MacroArgentinaDashboard/4.0'}});if(!r.ok)throw new Error(`${r.status}`);return await r.json();}finally{clearTimeout(t)}}
async function fetchText(url,ms=3500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{accept:'text/html','user-agent':'MacroArgentinaDashboard/4.0'}});if(!r.ok)throw new Error(`${r.status}`);return await r.text();}finally{clearTimeout(t)}}
function obs(x){if(Array.isArray(x))return x;if(Array.isArray(x?.data))return x.data;if(Array.isArray(x?.results))return x.results;if(x&&typeof x==='object')return [x];return []}
function latest2(x){const a=obs(x).map(r=>({date:String(r.fecha??r.date??r.updatedAt??''),value:Number(r.valor??r.value??r.venta??r.close??r.price)})).filter(r=>r.date&&Number.isFinite(r.value)).sort((a,b)=>a.date.localeCompare(b.date));const z=a.at(-1),p=a.at(-2);return z?{...z,previous:p?.value??null,changePct:p?.value?round((z.value/p.value-1)*100):null}:null}
async function risk(){try{const u=await fetchJson('https://api.argentinadatos.com/v1/finanzas/indices/riesgo-pais/ultimo');const v=Number(u?.valor??u?.value),d=String(u?.fecha??u?.date??'');if(Number.isFinite(v)&&d)return {date:d,value:v,changePct:Number.isFinite(Number(u?.variacion))?Number(u.variacion):null};}catch{}return {date:'2026-09-28',value:641,changePct:5.25,stale:true}}
async function mep(){for(const u of ['https://api.argentinadatos.com/v1/cotizaciones/dolares/bolsa/ultimo','https://api.argentinadatos.com/v1/cotizaciones/dolares/bolsa']){try{const x=latest2(await fetchJson(u));if(x)return x}catch{}}return {date:'2026-09-28',value:1552.5,changePct:null,stale:true}}
async function merval(){for(const u of ['https://zion.ar/api/v1/indicators/merval/history?limit=2','https://zion.ar/api/v1/indicators/merval/history?limit=5']){try{const x=latest2(await fetchJson(u));if(x)return x}catch{}}return {date:'2026-09-25',value:2893750.75,changePct:-1.57,stale:true}}
async function bna(){try{const html=await fetchText('https://www.bna.com.ar/Personas');const plain=html.replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/\s+/g,' ');const m=plain.match(/(\d{1,2}\/\d{1,2}\/\d{4})\s+Compra\s+Venta\s+Dolar U\.S\.A\s+([\d.,]+)\s+([\d.,]+)/i);if(m){const n=x=>Number(x.replace(/\./g,'').replace(',','.')),p=m[1].split('/');return {date:`${p[2]}-${p[1].padStart(2,'0')}-${p[0].padStart(2,'0')}`,buy:n(m[2]),sell:n(m[3]),changePct:null}}}catch{}return {date:'2026-09-28',buy:1495,sell:1545,changePct:null,stale:true}}
export default async()=>{const [a,b,c,d]=await Promise.allSettled([merval(),mep(),risk(),bna()]);const val=x=>x.status==='fulfilled'?x.value:null;return new Response(JSON.stringify({version:84,generatedAt:new Date().toISOString(),latest:{merval:val(a),dollar:val(b),risk:val(c),bna:val(d)}}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=60, stale-while-revalidate=86400','access-control-allow-origin':'*'}})};
